apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng
  namespace: stress-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stress-ng
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress-ng
    spec:
      containers:
      - image: alexeiled/stress-ng
        name: stress-ng
        command: ["/stress-ng"]
        args: ["-c", "2", "-l", "100", "-v"]
        resources:
          limits:
            cpu: 1000m
