# stress-ng-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stress-ng-service
spec:
  selector:
    app: stress-ng-webserver
  ports:
    - protocol: TCP
      port: 8080        # External port
      targetPort: 8080 # Port on the container
  type: LoadBalancer  # Can also be 'NodePort' if LoadBalancer is unavailable
