#FROM openjdk
FROM maven:3.9.0-amazoncorretto-19
COPY src JavaDocker
WORKDIR JavaDocker
RUN mkdir -p bin
RUN javac -d bin ./FillHeap90.java
WORKDIR bin
CMD ["java", "-Xms64m", "-Xmx128m", "FillHeap90"]
